name: Deploy Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Client to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to Client Directory
        run: cd client

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Build Client
        run: npm run build
        working-directory: client

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
        working-directory: client
