name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Server to Firebase Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        env:
          CI: true
        working-directory: server

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        # Dynamically create the firebase-key.json file from the GitHub secret
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/firebase-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Build Server
        run: npm run build
        working-directory: server

      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        working-directory: server
